### ISSUE TITLE
HUGE unordered list in presentation mode

### ISSUE THREAD

**Issue by jasonkeene** [pivotal-legacy/whiteboard#91]
I added some markdown unordered list items to the description of my event and they render out quite large!

<img width="1650" alt="screen shot 2016-04-20 at 9 15 26 am" src="https://cloud.githubusercontent.com/assets/161453/14679897/0775ad4a-06d9-11e6-8d13-857fd3661cf9.png">

**Comment by dsharp-pivotal** [comment]
I dug into this a little bit b/c this has been bugging me too.

This is due to the `.slide ul { font-size: 200% !important; }` this commit: afbedcae779d53144d8c28d474def008e2a13667

`<h1>` elements are even more ridiculously large. (Try adding a markdown `# Heading`)

We could just revert it, but I don't want to discount the concerns that precipitated the change. I can't view the story mentioned in that commit to see if it is still relevant.

CC'ing the authors to see if they remember any context:
@heimidal @cwang-pivotal @berlin-ab @dam5s

**Comment by berlin-ab** [comment]
My guess is that those rules were appropriate at the time, but six years
worth of changes did not consider presentation mode along the way.

Either that, or we messed up, but that was a long time ago.

**Comment by dsharp-pivotal** [comment]
@rlam-pivotal Is the pipeline running? I can't access jetway concourse. I don't see this change on whiteboard.

**Comment by rlam-pivotal** [comment]
Hi @dsharp-pivotal, it looks like the Concourse pipeline did not run and deploy the latest code to production. We'll investigate the issue and keep you posted.
